version: '3.3'
services:
  chain:
    container_name: mcl_node
    build:
      context: ./dockerfiles
      dockerfile: mcl.Dockerfile
      args:
      - PW=12345 #  Before building the docker service, change the following password for security reasons
      - CHAINLINK=https://github.com/marmarachain/marmara/releases/download/v1.1.6/MCL-linux.zip
    volumes:
      - ./chainfiles_mcl:/root/.komodo/MCL/
      - ./zcashparams:/root/.zcash-params
    ports:
      - "49155:22"  # Change the host port as you wish >> host:continer
    restart: always
  
  # chain_2:
  #   container_name: mcl_node_2
  #   build:
  #     context: ./dockerfiles
  #     dockerfile: mcl.Dockerfile
  #     args:
  #     - PW=securepw #  Before building the docker service, change the following password for security reasons
  #   volumes:
  #     - ./chainfiles_mcl_2:/root/.komodo/MCL/
  #     - ./zcashparams:/root/.zcash-params
  #   ports:
  #     - "491556:22" # Change the host port as you wish >> host:continer

